#Create two 
```{r}
#Create two vectors of different lengths
v1 <- c(5,6,1)
v2 <- c(10,11,12,13,15,14)
result= array(c(v1,v2))
result
```

```{r}
v1 = c(5,9,3,10,12)
v2 = c(10,11,12,14,13,15)
cnames = c("col1","col2","col3")
rnames = c("row1", "row2","row3")
mnames = c("Matrix1", "Matrix2")

#taking these vectoes as the input to the array
result = array(c(v1,v2),dim = c(3,3,2),dimnames = list(rnames, cnames,mnames))
result
```
```{r}
print(result)
```
```{r}
#Indexing 
print(result[1])

```
```{r}
#Apply function
#apply(x, margin, fun...)
# x is array or matrix
#Margin : take a value or range between 1 and 2 to define where to apply the function
#Margin = 1 : on rows
#Margin  =2 : on cols
#Margin = c(1,2) : on rows and cols
#fun : tells which function to apply
```


```{r}
m1 <- matrix(C <- (1:10),nrow = 5,ncol = 6)
m1
```


```{r}
#Columns sum using the apply function
a_m1 <- apply(m1,2,sum)
a_m1
```
```{r}
new.array <- array(c(v1,v2),dim = c(3,3,2))
print(new.array)
```
```{r}
v1 <- c(5,6,1)
v2 <- c(10,11,12,13,15,14)
result <- apply(new.array,c(1),sum)
print(result)
```

